services:
  anythingllm:
    image: mintplexlabs/anythingllm:1.9.0
    container_name: llm
    ports:
      - "3001:3001"
    volumes:
      - ./anythingllm:/app/server/storage
      - ./anythingllm/.env:/app/server/.env
      - ./anythingllm/collector/hotdir:/app/collector/hotdir
    environment:
      - STORAGE_DIR=/app/server/storage
